import Head from "next/head";
import useSound from "use-sound";

import { Image, Box } from "@chakra-ui/react";

export default function Home() {
  const [playWebsites] = useSound("cassidoo-websites.mp3");
  return (
    <Box
      w="100vw"
      h="100vh"
      d="flex"
      justifyContent="center"
      alignItems="center"
      flexDir="column"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Press the doo</h1>
      <Image
        boxSize="100px"
        objectFit="fit"
        src="/smiledoo.png"
        alt="Cassidy williams"
        onClick={playWebsites}
      />
    </Box>
  );
}
