import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSound from "use-sound";

export default function Home() {
  const [play] = useSound("/fbf.mp3");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={play}>play</button>
    </div>
  );
}
